SELECT RN, A.*
  FROM  (SELECT ROW_NUMBER() OVER (ORDER BY EMPLOYEE_ID DESC)AS RN, *
           FROM EMPLOYEES) A
 WHERE A.RN BETWEEN 1 AND 20;
 
 SELECT A.BOARD_NO, A.TITLE, A.CONTENT, A.MODIFIED_AT, A.CREATED_AT
   FROM (SELECT ROW_NUMBER() OVER (ORDER BY BOARD_NO DESC) AS RN, BOARD_NO, TITLE, CONTENT, MODIFIED_AT, CREATED_AT
         FROM BOARD_T)A
 WHERE A.RN BETWEEN 1 AND 20
 
